server:
  port: 9060
spring:
  application:
    name: config-client-dev

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9001/eureka/
  instance:
    prefer-ip-address: true
#    instance-id: micro-provider
